export const PERSONAL_INFO = {
  name: "Nikhil Kumar",
  title: "Software Engineer & Full Stack Developer",
  email: "palemnikkhilkumar@gmail.com",
  github: "https://github.com/nikhil938112",
  linkedin: "https://linkedin.com/in/nikhilgowd",
  instagram: "https://instagram.com/nikhilgowd",
  location: "India",
  bio: "Passionate Full Stack Developer crafting digital experiences that live at the intersection of creativity and technology. I build scalable web applications, explore AI integrations, and believe in code as a medium of art.",
  shortBio: "Building the future, one line of code at a time.",
};

export const ROLES = [
  "Full Stack Developer",
  "MERN Stack Engineer",
  "Problem Solver",
  "AI Enthusiast",
  "Future Builder",
  "React Developer",
  "Node.js Expert",
];

export const SKILLS = {
  Frontend: [
    { name: "React.js", level: 92, color: "#61DAFB" },
    { name: "Next.js", level: 88, color: "#FFFFFF" },
    { name: "TypeScript", level: 82, color: "#3178C6" },
    { name: "JavaScript", level: 95, color: "#F7DF1E" },
    { name: "Tailwind CSS", level: 90, color: "#38BDF8" },
    { name: "HTML5 / CSS3", level: 95, color: "#E34F26" },
  ],
  Backend: [
    { name: "Node.js", level: 88, color: "#339933" },
    { name: "Express.js", level: 85, color: "#FFFFFF" },
    { name: "REST APIs", level: 90, color: "#FF6B6B" },
    { name: "GraphQL", level: 70, color: "#E10098" },
  ],
  Database: [
    { name: "MongoDB", level: 88, color: "#47A248" },
    { name: "MySQL", level: 80, color: "#4479A1" },
    { name: "PostgreSQL", level: 72, color: "#336791" },
    { name: "Redis", level: 65, color: "#DC382D" },
  ],
  "Cloud & DevOps": [
    { name: "Docker", level: 75, color: "#2496ED" },
    { name: "AWS", level: 68, color: "#FF9900" },
    { name: "GitHub Actions", level: 78, color: "#2088FF" },
    { name: "Git", level: 92, color: "#F05032" },
  ],
  AI: [
    { name: "OpenAI APIs", level: 80, color: "#74AA9C" },
    { name: "Prompt Engineering", level: 85, color: "var(--galactic-pink)" },
    { name: "Generative AI", level: 78, color: "var(--cosmic-purple)" },
    { name: "LangChain", level: 65, color: "var(--neon-blue)" },
  ],
};

export const PROJECTS = [
  {
    id: 1,
    title: "MERN Thinkboard",
    tagline: "AI-powered collaborative note-taking platform",
    description: "A full-stack collaborative workspace where teams can create, share, and organize notes with AI-powered suggestions. Built with real-time sync and beautiful UI.",
    tech: ["React", "Node.js", "MongoDB", "Express", "Socket.io", "OpenAI"],
    github: "https://github.com/nikhil938112/mern-thinkboard",
    live: "#",
    color: "var(--cosmic-purple)",
    planetColor: "#8B5CF6",
    features: ["Real-time collaboration", "AI note suggestions", "Rich text editor", "Team workspaces"],
    metrics: "500+ notes created, 98% uptime",
    image: "/projects/thinkboard.png",
  },
  {
    id: 2,
    title: "ApplyBot",
    tagline: "AI-driven job application automation engine",
    description: "Intelligent job application bot that tracks applications, generates tailored cover letters using AI, and provides analytics on your job search journey.",
    tech: ["React", "Python", "Selenium", "OpenAI", "MongoDB", "FastAPI"],
    github: "https://github.com/nikhil938112/applybot",
    live: "#",
    color: "var(--neon-blue)",
    planetColor: "#06B6D4",
    features: ["Auto-fill applications", "AI cover letters", "Application tracking", "Analytics dashboard"],
    metrics: "200+ applications automated",
    image: "/projects/applybot.png",
  },
  {
    id: 3,
    title: "Chat App",
    tagline: "Real-time messaging platform with E2E encryption",
    description: "Feature-rich chat application supporting real-time messaging, group chats, file sharing, and end-to-end encryption. Supports 1000+ concurrent users.",
    tech: ["React", "Node.js", "Socket.io", "MongoDB", "JWT", "Cloudinary"],
    github: "https://github.com/nikhil938112/chatt-app",
    live: "#",
    color: "var(--galactic-pink)",
    planetColor: "#EC4899",
    features: ["Real-time messaging", "Group chats", "File sharing", "E2E encryption"],
    metrics: "1000+ concurrent users",
    image: "/projects/chatapp.png",
  },
  {
    id: 4,
    title: "Weather App",
    tagline: "Hyper-local weather forecasting with beautiful UI",
    description: "A stunning weather application with 7-day forecasts, hourly data, interactive maps, and animated weather conditions using OpenWeatherMap API.",
    tech: ["React", "TypeScript", "OpenWeatherMap API", "Chart.js", "Tailwind"],
    github: "https://github.com/nikhil938112/weatherapp",
    live: "#",
    color: "#10B981",
    planetColor: "#34d399",
    features: ["7-day forecast", "Hourly data", "Interactive maps", "Animated conditions"],
    metrics: "10,000+ API calls served",
    image: "/projects/weather.png",
  },
  {
    id: 5,
    title: "Pernstack App",
    tagline: "Full-stack PERN application with auth & dashboard",
    description: "Production-ready PERN (PostgreSQL, Express, React, Node) stack application with JWT authentication, role-based access control, and an admin dashboard.",
    tech: ["React", "Express", "PostgreSQL", "Node.js", "JWT", "Redux"],
    github: "https://github.com/nikhil938112/Pernstack",
    live: "#",
    color: "var(--electric-cyan)",
    planetColor: "var(--electric-cyan)",
    features: ["JWT Authentication", "Role-based access", "Admin dashboard", "RESTful APIs"],
    metrics: "Production deployed",
    image: "/projects/pernstack.png",
  },
  {
    id: 6,
    title: "Analytics Dashboard",
    tagline: "Real-time data visualization platform",
    description: "Interactive analytics dashboard with real-time charts, KPI tracking, custom reports, and exportable data visualizations built for business intelligence.",
    tech: ["React", "D3.js", "Node.js", "MongoDB", "Recharts", "WebSocket"],
    github: "https://github.com/nikhil938112/dashboard",
    live: "#",
    color: "#8B5CF6",
    planetColor: "#A78BFA",
    features: ["Real-time charts", "KPI tracking", "Custom reports", "Data export"],
    metrics: "50+ chart types supported",
    image: "/projects/dashboard.png",
  },
  {
    id: 7,
    title: "AI Profile Detection",
    tagline: "Detect fake & LLM-generated social media profiles",
    description: "An AI-powered system to detect fraudulent and AI-generated social media profiles using Google BigQuery, Vision API, and Gemini AI. Includes a browser extension for real-time risk scoring and suspicious-profile alerts without leaving the browser.",
    tech: ["Google BigQuery", "Gemini AI", "Vision API", "K-Means", "Autoencoders", "Browser Extension", "Genetic Algorithm"],
    github: "#",
    live: "#",
    color: "#F97316",
    planetColor: "#FB923C",
    features: ["LLM profile fingerprinting", "Real-time browser extension", "K-Means clustering", "Autoencoder anomaly detection", "Genetic algorithm optimization", "Risk score alerts"],
    metrics: "Rule-based + ML hybrid detection pipeline",
    image: "/projects/ai-detection.png",
  },
  {
    id: 8,
    title: "Mental Health Tracker",
    tagline: "Child-friendly wellness & mood tracking platform",
    description: "A child-friendly digital mental-health platform featuring mood tracking, guided meditation modules, and emotion trend analytics. Built with parental monitoring dashboards to surface emotion trends and usage insights, with a fully responsive UI for accessibility across all devices.",
    tech: ["JSP", "JDBC", "Java", "HTML5", "CSS3", "Bootstrap", "JavaScript", "MySQL"],
    github: "#",
    live: "#",
    color: "#14B8A6",
    planetColor: "#2DD4BF",
    features: ["Mood & emotion tracking", "Guided meditation modules", "Parental monitoring dashboard", "Emotion trend analytics", "Responsive cross-device UI", "Usage insights for guardians"],
    metrics: "Full-stack Java web app with analytics dashboard",
    image: "/projects/mental-health.png",
  },
];

export const EXPERIENCE = [
  {
    id: 1,
    role: "Full Stack Developer",
    company: "Freelance / Self-Employed",
    period: "2023 – Present",
    type: "Freelance",
    description: "Building production-ready web applications for clients worldwide. Specializing in MERN stack, Next.js, and AI integrations.",
    highlights: ["Delivered 10+ client projects", "100% on-time delivery", "5-star client ratings"],
    color: "var(--cosmic-purple)",
  },
  {
    id: 2,
    role: "MERN Stack Intern",
    company: "Tech Startup",
    period: "2023",
    type: "Internship",
    description: "Contributed to building scalable REST APIs and React frontends. Worked with agile teams on feature development and code reviews.",
    highlights: ["Built 5 REST API endpoints", "Improved app performance by 40%", "Collaborated in agile sprints"],
    color: "var(--neon-blue)",
  },
  {
    id: 3,
    role: "Open Source Contributor",
    company: "GitHub Community",
    period: "2022 – Present",
    type: "Open Source",
    description: "Active contributor to open source projects. Maintained personal projects and contributed bug fixes and features to community repos.",
    highlights: ["50+ GitHub contributions", "3 personal OSS projects", "Active in developer communities"],
    color: "var(--galactic-pink)",
  },
  {
    id: 4,
    role: "B.Tech Computer Science",
    company: "University",
    period: "2021 – 2025",
    type: "Education",
    description: "Bachelor's in Computer Science with focus on Data Structures, Algorithms, Web Development, and Database Management Systems.",
    highlights: ["Strong DSA foundation", "Web dev specialization", "Final year project: AI-powered app"],
    color: "#10B981",
  },
];

export const ACHIEVEMENTS = [
  { title: "Projects Shipped", value: "12+", icon: "🚀" },
  { title: "GitHub Stars", value: "50+", icon: "⭐" },
  { title: "Technologies Mastered", value: "20+", icon: "⚡" },
  { title: "Problems Solved", value: "200+", icon: "🧠" },
];

export const AI_ORB_FAQ = [
  {
    question: "Who is Nikhil Kumar?",
    answer: "Nikhil is a Full Stack Developer specializing in the MERN stack, Next.js, and AI integrations. He builds scalable, beautiful web applications.",
  },
  {
    question: "What are his top skills?",
    answer: "React, Next.js, Node.js, MongoDB, TypeScript, and AI APIs (OpenAI). He's also exploring generative AI and cloud technologies.",
  },
  {
    question: "Is he open to work?",
    answer: "Yes! Nikhil is actively seeking exciting opportunities — full-time roles, internships, and freelance projects.",
  },
  {
    question: "What's his best project?",
    answer: "MERN Thinkboard is his most comprehensive project — a full-stack collaborative note platform with AI features and real-time sync.",
  },
  {
    question: "How to contact him?",
    answer: "Reach out via the Contact section below, or email at palemnikkhilkumar@gmail.com. He typically responds within 24 hours!",
  },
];
