// ─── All 10 Portfolio Themes ───────────────────────────────────────────────

export interface Theme {
  id: string;
  name: string;
  emoji: string;
  description: string;
  preview: { bg: string; primary: string; secondary: string };
  vars: Record<string, string>;
}

export const THEMES: Theme[] = [
  {
    id: "cyberpunk",
    name: "Cyberpunk Neon",
    emoji: "🟣",
    description: "Hot pink & yellow on pure black",
    preview: { bg: "#000000", primary: "#f0abfc", secondary: "#facc15" },
    vars: {
      "--space-black":   "#000000",
      "--deep-space":    "#0a000a",
      "--cosmic-purple": "#c026d3",
      "--neon-blue":     "#f0abfc",
      "--electric-cyan": "#facc15",
      "--galactic-pink": "#e879f9",
      "--star-white":    "#fdf4ff",
      "--nebula-violet": "#4a044e",
      "--aurora-green":  "#34d399",
    },
  },
  {
    id: "amber",
    name: "Amber Gold",
    emoji: "🟠",
    description: "Luxurious gold on dark espresso",
    preview: { bg: "#0d0a06", primary: "#f59e0b", secondary: "#d97706" },
    vars: {
      "--space-black":   "#0d0a06",
      "--deep-space":    "#120d07",
      "--cosmic-purple": "#d97706",
      "--neon-blue":     "#f59e0b",
      "--electric-cyan": "#fbbf24",
      "--galactic-pink": "#b45309",
      "--star-white":    "#fef3c7",
      "--nebula-violet": "#451a03",
      "--aurora-green":  "#34d399",
    },
  },
  {
    id: "matrix",
    name: "Matrix Emerald",
    emoji: "🟢",
    description: "Neon green on deep black",
    preview: { bg: "#020f07", primary: "#22c55e", secondary: "#a3e635" },
    vars: {
      "--space-black":   "#020f07",
      "--deep-space":    "#041409",
      "--cosmic-purple": "#16a34a",
      "--neon-blue":     "#22c55e",
      "--electric-cyan": "#a3e635",
      "--galactic-pink": "#4ade80",
      "--star-white":    "#f0fdf4",
      "--nebula-violet": "#052e16",
      "--aurora-green":  "#34d399",
    },
  },
  {
    id: "crimson",
    name: "Crimson Noir",
    emoji: "🔴",
    description: "Crimson red & rose on near-black",
    preview: { bg: "#0d0205", primary: "#ef4444", secondary: "#fb7185" },
    vars: {
      "--space-black":   "#0d0205",
      "--deep-space":    "#110307",
      "--cosmic-purple": "#dc2626",
      "--neon-blue":     "#ef4444",
      "--electric-cyan": "#fb7185",
      "--galactic-pink": "#f87171",
      "--star-white":    "#fff1f2",
      "--nebula-violet": "#450a0a",
      "--aurora-green":  "#34d399",
    },
  },
  {
    id: "arctic",
    name: "Arctic Ice",
    emoji: "🩵",
    description: "Ice blue & cyan on slate navy",
    preview: { bg: "#0a0f1e", primary: "#38bdf8", secondary: "#67e8f9" },
    vars: {
      "--space-black":   "#0a0f1e",
      "--deep-space":    "#0d1426",
      "--cosmic-purple": "#0284c7",
      "--neon-blue":     "#38bdf8",
      "--electric-cyan": "#67e8f9",
      "--galactic-pink": "#7dd3fc",
      "--star-white":    "#f0f9ff",
      "--nebula-violet": "#082f49",
      "--aurora-green":  "#34d399",
    },
  },
  {
    id: "rust",
    name: "Rust & Steel",
    emoji: "🟤",
    description: "Rust orange & copper on charcoal",
    preview: { bg: "#0f0d0b", primary: "#ea580c", secondary: "#f97316" },
    vars: {
      "--space-black":   "#0f0d0b",
      "--deep-space":    "#14100d",
      "--cosmic-purple": "#c2410c",
      "--neon-blue":     "#ea580c",
      "--electric-cyan": "#f97316",
      "--galactic-pink": "#fb923c",
      "--star-white":    "#fff7ed",
      "--nebula-violet": "#431407",
      "--aurora-green":  "#34d399",
    },
  },
  {
    id: "cherry",
    name: "Cherry Blossom",
    emoji: "🌸",
    description: "Soft pink & blush on deep graphite",
    preview: { bg: "#0d0a0e", primary: "#f472b6", secondary: "#fbcfe8" },
    vars: {
      "--space-black":   "#0d0a0e",
      "--deep-space":    "#120d14",
      "--cosmic-purple": "#db2777",
      "--neon-blue":     "#f472b6",
      "--electric-cyan": "#fbcfe8",
      "--galactic-pink": "#f9a8d4",
      "--star-white":    "#fdf2f8",
      "--nebula-violet": "#500724",
      "--aurora-green":  "#34d399",
    },
  },
  {
    id: "solaris",
    name: "Solaris Gold",
    emoji: "🟡",
    description: "Yellow-gold & orange neon glow",
    preview: { bg: "#0c0906", primary: "#eab308", secondary: "#fb923c" },
    vars: {
      "--space-black":   "#0c0906",
      "--deep-space":    "#110d08",
      "--cosmic-purple": "#ca8a04",
      "--neon-blue":     "#eab308",
      "--electric-cyan": "#fb923c",
      "--galactic-pink": "#fde047",
      "--star-white":    "#fefce8",
      "--nebula-violet": "#422006",
      "--aurora-green":  "#34d399",
    },
  },
  {
    id: "mono",
    name: "Monochrome Elite",
    emoji: "⚪",
    description: "Pure white neon on true black",
    preview: { bg: "#030303", primary: "#f8fafc", secondary: "#94a3b8" },
    vars: {
      "--space-black":   "#030303",
      "--deep-space":    "#0a0a0a",
      "--cosmic-purple": "#94a3b8",
      "--neon-blue":     "#f8fafc",
      "--electric-cyan": "#cbd5e1",
      "--galactic-pink": "#64748b",
      "--star-white":    "#e2e8f0",
      "--nebula-violet": "#0f172a",
      "--aurora-green":  "#6ee7b7",
    },
  },
  {
    id: "ocean",
    name: "Deep Ocean",
    emoji: "🌊",
    description: "Teal & aqua on abyss blue",
    preview: { bg: "#020c14", primary: "#14b8a6", secondary: "#2dd4bf" },
    vars: {
      "--space-black":   "#020c14",
      "--deep-space":    "#041018",
      "--cosmic-purple": "#0d9488",
      "--neon-blue":     "#14b8a6",
      "--electric-cyan": "#2dd4bf",
      "--galactic-pink": "#5eead4",
      "--star-white":    "#f0fdfa",
      "--nebula-violet": "#042f2e",
      "--aurora-green":  "#34d399",
    },
  },
];

export const DEFAULT_THEME = THEMES.find((t) => t.id === "amber")!;
